### ISSUE TITLE
color presets

### ISSUE THREAD

**Issue by argyleink** [argyleink/gradient-style#22]
stuff like this, premade

```css
.modern-gradient {
  background-image: 
    linear-gradient(
      to top right in oklch shorter hue, 
      color(display-p3 100% 0% 100%),
      color(display-p3 100% 0% 50%)
    )
  ;
}
```
